# doi:10.18419/darus-3801

name: Dataverse Sync

on: [push, release]

jobs:
  dv-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Synchronize to DV
      uses: ./
      with:
        dataverse_url: "https://darus.uni-stuttgart.de"
        api_token: ${{ secrets.DV_API_TOKEN }}
        persistent_id: "doi:10.18419/darus-3801"