# doi:10.18419/darus-3801

name: Test and publish

on:
    push:
        branches:
        - main
    release:
        types:
        - published

jobs:
  dv-sync:
    runs-on: ubuntu-latest
    env:
      DV_API_TOKEN: ${{ secrets.DV_API_TOKEN }}
      DV_URL: "https://darus.uni-stuttgart.de"
      DV_PID: "doi:10.18419/darus-3801"
    steps:
    - uses: actions/checkout@v2
    - name: Synchronize to DV
      uses: ./
      with:
        dataverse_url: ${{ env.DV_URL }}
        api_token: ${{ env.DV_API_TOKEN }}
        persistent_id: ${{ env.DV_PID }}
    - name: "Install Python"
      uses: "actions/setup-python@v2"
      with:
        python-version: "3.11"
    - name: Test content
      run: |
        python3 .github/workflows/scripts/check_content.py